spring.application.name=financial-system
sync.server.url=http://172.16.2.131:8081/sync
spring.datasource.url=jdbc:mysql://localhost:3306/fd
spring.datasource.username=root
spring.datasource.password=REAL MYSQL PASSWORD

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update


backup.folder=C:\\CurrencyExchange\\Backups

upload.folder=C:\\CurrencyExchange\\uploads\\logos

mysql.database=fd

mysql.username=root

mysql.password=REAL MYSQL PASSWORD

mysql.bin.path=C:\\Program Files\\MySQL\\MySQL Server 8.0\\bin
